### ISSUE TITLE
TypeError: grid.mongo.GridStore is not a constructor

### ISSUE THREAD

**Issue by bferraro78** [aheckmann/gridfs-stream#112]
Hello,

While trying to upload a mp4 video file to my mongoDB, I receive this error...

```
D:\User\Desktop\server\node_modules\mongodb\lib\mongodb\connection\base.js:245
        throw message;
        ^

TypeError: grid.mongo.GridStore is not a constructor
    at new GridWriteStream (D:\User\Desktop\server\node_modules\gridfs-stream\lib\writestream.js:64:16)
    at Grid.createWriteStream (D:\User\Desktop\server\node_modules\gridfs-stream\lib\index.js:42:10)
    at D:\User\Desktop\server\accountVideosDriver.js:89:25
    at D:\User\Desktop\server\accountVideosDriver.js:72:10
    at D:\User\Desktop\server\accountVideosDriver.js:62:11
    at D:\User\Desktop\server\node_modules\mongodb\lib\mongodb\collection\core.js:125:9
    at D:\User\Desktop\server\node_modules\mongodb\lib\mongodb\db.js:1131:7
    at D:\User\Desktop\server\node_modules\mongodb\lib\mongodb\db.js:1847:9
    at Server.Base._callHandler (D:\User\Desktop\server\node_modules\mongodb\lib\mongodb\connection\base.js:445:41)
    at D:\User\Desktop\server\node_modules\mongodb\lib\mongodb\connection\server.js:478:18

```

Here is where I initialize my drivers and requirements in index.js...

```
var http = require('http'), https = require('https'), express = require('express'), 
path = require('path'), fs = require('fs'), apn = require('apn');

var MongoClient = require('mongodb').MongoClient,
Server = require('mongodb').Server,
CollectionDriver = require('./collectionDriver').CollectionDriver,
FileDriver = require('./fileDriver').FileDriver,
AccountPicturesDriver = require('./accountPicturesDriver').AccountPicturesDriver,
AccountVideosDriver = require('./accountVideosDriver').AccountVideosDriver,
EntryVideosDriver = require('./entryVideosDriver').EntryVideosDriver,
ObjectID = require('mongodb').ObjectID,
GridStore = require('mongodb').GridStore,
Grid = require('gridfs-stream');

var app = express(); // create Express.js object
app.set('port', process.env.PORT || 3000);
// app.set('host', '0.0.0.0');
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');
app.use(express.bodyParser());

var mongoHost = 'localHost'; 
var mongoPort = 27017;

var fileDriver;
var collectionDriver;
var accountPicturesDriver;
var accountVideosDriver;
var entryVideosDriver;
var gridfs;

var mongoClient = new MongoClient(new Server(mongoHost, mongoPort)); 
mongoClient.open(function(err, mongoClient) { 
  if (!mongoClient) {
      console.error("Error! Exiting... Must start MongoDB first");
      process.exit(1); 
  }
  var db = mongoClient.db("MyDatabase");
  gridfs = Grid(db, mongoClient);
  fileDriver = new FileDriver(db);
  collectionDriver = new CollectionDriver(db); 
  accountPicturesDriver = new AccountPicturesDriver(db);
  accountVideosDriver = new AccountVideosDriver(db, gridfs);
  entryVideosDriver = new EntryVideosDriver(db);

});`
```

This is the post called from my mobile app in index.js...
```
app.post('/accountVideos', function(req,res) {
  accountVideosDriver.handleUploadRequestAccountVideo(req,res);
});
```

Finally, here is the function where I call the createWriteStream . AccountVideosDriver.js...

```
AccountVideosDriver.prototype.handleUploadRequestAccountVideo = function(req, res) { //1
    var ctype = req.get("content-type"); //2
    var ext = ctype.substr(ctype.indexOf('/')+1); //3
    var grid = this.gridfs; // Grid() object initialized in index.js

    if (ext) {ext = '.' + ext; } else {ext = '';}
    this.getNewFileId({'content-type':ctype, 'ext':ext}, function(err,id) { //4
        if (err) { res.send(400, err); 
        } else {           
          var filename = id + ext; //5
          filePath = __dirname + '/accountVideos/' + filename; //6

          var ws = grid.createWriteStream( { // error here!!!!!
            filename: filename
          });
          fs.createReadStream('/accountVideos/'+filename).pipe(ws);

           var writable = fs.createWriteStream(filePath); //7
           req.pipe(writable); //8
                 req.on('end', function (){ //9
                    res.send(201,{'_id':id});
                 });               
                 writable.on('error', function(err) { //10
                    res.send(500,err);
                 });
        }
    });
};

```
I am believe that something might be wrong when I am creating my Grid object. Debugging has told me that it most certainly is not undefined or null. 

Please ask any questions you may have. Thanks for reading.

**Comment by healiha** [comment]
Looking at this, the first thing I wonder is if `var grid = this.gridfs;` is defined or not?
