### ISSUE TITLE
TypeError: Cannot read property 'ObjectID' of undefined

### ISSUE THREAD

**Issue by vasiliy0s** [aheckmann/gridfs-stream#74]
After update to `Mongoose#4.0.1` I had error:
```sh
/Users/temp/projects/greeder-sources/node_modules/gridfs-stream/lib/readstream.js:54
new grid.mongo.GridStore(grid.db, this.id || new grid.mongo.BSONPure.ObjectID,
                                                                    ^
TypeError: Cannot read property 'ObjectID' of undefined
    at Stream.GridReadStream (/Users/temp/projects/greeder-sources/node_modules/gridfs-stream/lib/readstream.js:54:85)
    at Grid.createReadStream (/Users/temp/projects/greeder-sources/node_modules/gridfs-stream/lib/index.js:52:10)
    at checkFound (/Users/temp/projects/greeder-sources/controllers/controllers/get_image.js:53:14)
    at fn (/Users/temp/projects/greeder-sources/node_modules/async/lib/async.js:641:34)
    at Immediate._onImmediate (/Users/temp/projects/greeder-sources/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

My _[get_image]_ controllers using `gfs` as it
```js
...
    function checkFound (found, gfsQuery, next) {
      if (!found) {
        return res.status(404).end('Not found');
      }
      db.gfs.createReadStream(gfsQuery)
        .on('error', next)
        .pipe(res);
    },
...
```

My GridFS initialization same as:
```js
    connection.once('open', function () {
      db.gfs = new GridFS(connection.db, mongoose.mongo);
      console.log(app._logPrefix(), 'GridFS connected with Mongoose database connection'.green);
    });

```

For fix this probliem I create patch:
```diff
diff --git a/db/index.js b/db/index.js
index 9fd49b6..f2e2efc 100644
--- a/db/index.js
+++ b/db/index.js
@@ -1,6 +1,7 @@
 'use strict';
 
 var mongoose = require('mongoose')
+  , BSONPure = require('bson').BSONPure
   , modelsReader = require('./models')
   , GridFS = require('gridfs-stream');
 
@@ -23,6 +24,8 @@ var db = module.exports = function (app) {
     });
 
     connection.once('open', function () {
+      mongoose.mongo.BSONPure = BSONPure;
       db.gfs = new GridFS(connection.db, mongoose.mongo);
       console.log(app._logPrefix(), 'GridFS connected with Mongoose database connection'.green);
     });

```

**Comment by Reggino** [comment]
This scenario seems covered by unit tests, so it may have something to do with your installation...

If you still think this is not the case, could you let us know your node.js version and provide a pull request for this exact use case? Thanks.

**Comment by vasiliy0s** [comment]
Yes, it is problem caused after upgrade to _Mongoose#4.0.1_ (with _mongodb#2_). I found `BSONPure` in [bson](https://www.npmjs.com/package/bson) package instead `mongodb`.

My installation at now (mongodb is as dependency of mongoose):
```sh
➜ node -v
v0.12.0

➜ npm -v
2.7.1

➜ npm list | grep mongoose
npm├─┬ mongoose@4.0.1

➜ npm list | grep mongodb 
npm│ ├─┬ mongodb@2.0.24
│ │ ├─┬ mongodb-core@1.1.20
```

**Comment by heavyk** [comment]
I was having the same error. I patched it the same way you did.. just add BSONPure on to mongo before passing it off to gridfs-stream

```js
mongo.BSONPure = require('bson').BSONPure
```

**Comment by heavyk** [comment]
so, @Reggino is right. after having a look a little deeper, I found out that another lib I was using, `gridfs` was loading an old version which was fucking things up... sorry...

```
gridfs@0.0.2 node_modules/gridfs
└── gridfs-stream@0.5.3
```

you probably have something else loading an old version of mongodb like I had ...
cheers

**Comment by mdsajidnewaj** [comment]
creator: { type: Schema.types.ObjectID, ref: 'User'},
TypeError: Cannot read property 'ObjectID' of undefined

**Comment by stableShip** [comment]
change `Schema.types.ObjectID ` to `Schema.ObjectId` @mdsajidnewaj
